### ISSUE TITLE
[BUG] CI fails due to actions/setup-python not finding version 3.10.5

### ISSUE THREAD

**Issue by AutonomicPerfectionist** [CMakePP/CMinx#105]
**Describe the bug**
CI failed on #100 due to the setup-python action not finding the version of python the workflow needs.

**To Reproduce**
1. Make a PR
2. Bump for CI
3. Observe error

**Expected behavior**
Our CI should not fail to find a version of python

**Additional context**
It appears we are still using version 1 of setup-python, the action is now on version 4. It's possible upgrading the workflow would fix the issue

**Comment by ryanmrichard** [comment]
Best I can tell, for each Python 3.x the action only knows about the version 3.x.y with the largest value of y. Point being, 3.10.5 used to be the version the action knew about, but I guess they just released version 3.10.6. What happens if we drop the revisions from the Python version (i.e., specify we want Python 3.8, 3.9, and 3.10)?

**Comment by ryanmrichard** [comment]
(you're also welcome to bump the version of the action if you want to)
