### ISSUE TITLE
Install Instructions

### ISSUE THREAD

**Issue by ryanmrichard** [CMakePP/CMinx#38]
I'm going through and touching up the documentation in preparation for a 1.0 release. I have some questions about https://cmakepp.github.io/CMinx/quickstart.html#installing. Do we still need to manually install `wheel`? If so, is there something I can link to in case a reader has the same question?

**Comment by AutonomicPerfectionist** [comment]
@ryanmrichard installing Wheel manually is only required for certain systems, usually it is automatically available but on, for instance, Ubuntu 20.04 it is not. It also cannot just be added to the dependencies because it is used by Pip itself to build source-only distributions, and so it must be installed separately and before everything else. There's not really an easy way to determine whether the command will be needed or not, sometimes the virtual environment has it and sometimes not. I figured it would just be easiest to tell users to install it in the virtual environment no matter their configuration, since it will do nothing if it's already there.

From what I can gather it has something to do with the python version being used, on my systems those with Python 3.8 exhibit the issue and those with 3.9 do not, as well as those with 3.7 or older. This is also corroborated by [this StackOverflow](https://stackoverflow.com/questions/69369669/python-3-venv-and-the-wheel-package)

**Comment by ryanmrichard** [comment]
Thanks for the clarification.
