### ISSUE TITLE
CMake Build Issues

### ISSUE THREAD

**Issue by ryanmrichard** [CMakePP/CMinx#39]
When I run:

```
cmake -S. -B build -DCMAKE_INSTALL_PREFIX=/where/I/want/to/install
cmake --build build
```
(in the root dir of CMinx) there's a couple things I note:
- the configure step actually builds CMinx (should be done in the build step)
- there's a `__pycache__` directory left in the source folder (should be generated in the build directory if at all possible)
- and CMinx is actually installed (CMinx shouldn't be installed during the build phase, but rather during the install phase)

I believe the latter point is why
```
cmake --install build
```
doesn't do anything, but I could be wrong.

**Comment by AutonomicPerfectionist** [comment]
Turns out I had my "watch" github settings incorrect for this repo so I entirely missed this issue, sorry.

The building and installation of CMinx is a bit complicated due to its pythonic nature. What configure currently does is it creates the internal virtual environment and downloads dependencies into it. I wasn't sure if this qualifies as configuring or building, but it should be noted dependencies must be downloaded before docs can be built, since we use the local repo to build them instead of pulling from master again. In the case of external repos using CMinx they will also require those dependencies. As far as I understand FetchContent will also build the downloaded project, correct?

**Comment by ryanmrichard** [comment]
No worries, the remaining issues on this repo aren't that pressing. 

Personally I feel that the obtaining of dependencies (through PIP or otherwise) should happen during the build phase; however, I have seen a number of projects which do it during the configure phase, so I wouldn't go so far as to say that's wrong. Since the CMake build wraps the Python build, which is a one shot build from CMake's perspective, I'd just do it all during the build phase and use a staging directory as the install directory for the build step (a directory like `build/stage/install_prefix`). The install step then copies `build/stage/install_prefix` to `install_prefix`. This assumes that executable created during the build step is relocatable; if it's not, and since the build is so quick anyways, we can just cheat for now and run a second build which installs it to the correct location. Testing should use the executable in the staging directory.
