### ISSUE TITLE
Fix coverage (why's it showing 0%)

### ISSUE THREAD

**Issue by ryanmrichard** [CMakePP/CMinx#46]

**Comment by AutonomicPerfectionist** [comment]
Issue appears to have not been resolved by #52, according to Github Action logs the coverage execution succeeded and uploaded results to codecov.io, but looking in the codecov dashboard shows a nondescript error page. Downloading the coverage report shows correct coverage data. Clicking the commit ID in codecov to compare shows a "missing base report" error. Perhaps it's because we weren't uploading coverage data for the last few commits?

**Comment by ryanmrichard** [comment]
As stupid as this perhaps sounds, I wouldn't call the issue resolved until the little badge displays the coverage again. I'm totally fine doing it some other way if CodeCov isn't going to cooperate.

**Comment by AutonomicPerfectionist** [comment]
Upon further investigation I have found that the badge shows 0% because no coverage reports are being uploaded for the main branch, only for other branches during pull requests. This should be fixable by making the `pip_install` job run whenever there are new commits on master, rather than just on pull requests to master
