### ISSUE TITLE
Getting `[22618] INTERNAL ERROR: cannot create temporary directory!`

### ISSUE THREAD

**Issue by ni-dschiller** [CMakePP/CMinx#59]
**Describe the bug**
Not sure what I changed but when executing `cminx -o docs -r ../mycmakestuff` I get this error now:
```
[22618] INTERNAL ERROR: cannot create temporary directory!
```
**To Reproduce**
1. Checkout latest CMinx
2. Run `cminx -o docs -r ../mycmakestuff`
3. See error

**Expected behavior**
`.rst` Files should be created

**Comment by AutonomicPerfectionist** [comment]
Hmm, none of our code directly creates temporary directories except during the build phase, so that's quite unexpected. My guess is one of the libraries we're using like Antlr is doing that silently, I will have to do some debugging either late tonight or some time tomorrow

**Comment by AutonomicPerfectionist** [comment]
@ni-dschiller can you confirm for me whether the output directory is created or not?

**Comment by ni-dschiller** [comment]
Hey Branden, no I can not see that the `docs` folder gets created. I also tried `sudo cminx -o docs -r ../mycmakestuff`, but same error.

**Comment by ni-dschiller** [comment]
When I search for the error in Google I find this one https://github.com/docker/compose/issues/3262 and they talk about `pyinstaller` which leads me to this one https://github.com/pyinstaller/pyinstaller/issues/4423. Not sure if `pyinstaller` is involved.

**Comment by ni-dschiller** [comment]
I also get this error by directly executing cminx:
```
dirk.schiller@C02DT9UMML7H docs % cminx
[24609] INTERNAL ERROR: cannot create temporary directory!
```

**Comment by ni-dschiller** [comment]
I also just tried to reinstall cminx like descriped here https://cmakepp.github.io/CMinx/installation.html

I remember the last bigger changes on my system were when I installed `pandoc` to convert the `.rst` files to `.md` for `MkDocs`. To install `pandoc` I used `brew` and there was an installation error and `brew` informed me to use the following command to process with the installation of `pandoc`:

```
sudo chown -R $(whoami) /usr/local/bin /usr/local/etc /usr/local/sbin
```

Maybe this command changed something which makes `cminx` stop working.

**Comment by ni-dschiller** [comment]
I could fix it by reinstalling `cminx` like described here but without the virtual environment:

```
git clone https://github.com/CMakePP/CMinx.git
cd CMinx
pip3 install wheel
pip3 install .
```

**Comment by AutonomicPerfectionist** [comment]
@ni-dschiller looks like you figured it out, we do use PyInstaller for the standalone binary that's built with cmake/make. How PyInstaller works is it extracts all the files into a temporary directory before running them, we set this temporary directory to `${CMAKE_INSTALL_PREFIX}/bin/.cminx`, so if your prefix was `/usr/local` then your previous `chown` command would certainly cause issues with it.

**Comment by ryanmrichard** [comment]
@AutonomicPerfectionist if I'm following this right the problem is extracting the CMinx installation. For my own edification when does this extraction occur? Is it as part of the installation process itself, or is it done every time you run CMinx? If the former that's fine, but if it's the latter, I don't think that's a good idea. Programs usually get installed to places that require admin access, so having CMinx assume it can make a directory next to its install location is probably going to force people to have to run the program with admin privileges (although that alone didn't seem to suffice either). If we have to make temporary files it's probably better to make them in `/tmp` on Linux, the directory CMinx is running in (I think this what most Python packages do), or in the user's home directory. Regardless of the option putting them in a directory `.cminx` is probably the way to go.

**Comment by AutonomicPerfectionist** [comment]
@ryanmrichard the extraction occurs at every run, and the directory is specified at build time due to how PyInstaller works. With that in mind, it turns out PyInstaller can figure out where to extract the files on its own, using the system-specific tmp folder. That should be pretty easy to switch to

**Comment by ryanmrichard** [comment]
@AutonomicPerfectionist sounds good to me.
